

/* Create Tables */

CREATE TABLE ORDER_ITEM
(
	ORDER_ITEM_NO number(4) NOT NULL,
	ORDER_NO number(4,0) NOT NULL,
	PRODUCT_NO number(4) NOT NULL,
	ORDER_ITEM_QUANTITY number(8),
	ORDER_ITEM_PRICE number(8),
	PRIMARY KEY (ORDER_ITEM_NO)
);


CREATE TABLE SEMI_CART_ITEMS
(
	CART_ITEM_NO number(4,0) NOT NULL,
	USER_NO number(4,0) NOT NULL,
	PRODUCT_NO number(4) NOT NULL,
	CART_ITEM_CREATED_DATE date DEFAULT SYSDATE,
	PRIMARY KEY (CART_ITEM_NO)
);


CREATE TABLE SEMI_NOTICES
(
	NOTICE_NO number(4,0) NOT NULL,
	NOTICE_TITLE varchar2(255) NOT NULL,
	NOTICE_CONTENT long NOT NULL,
	NOTICE_CREATED_DATE date DEFAULT SYSDATE,
	NOTICE_VIEW_COUNT number(8) DEFAULT 0,
	PRIMARY KEY (NOTICE_NO)
);


CREATE TABLE SEMI_ORDERS
(
	ORDER_NO number(4,0) NOT NULL,
	ORDER_CREATED_DATE date DEFAULT SYSDATE,
	ORDER_STATUS varchar2(100),
	ORDER_TOTAL_PRICE number(8),
	USED_POINT number(8),
	TOTAL_PAYMENT_PRICE number(8),
	DEPOSIT_POINT number(8),
	PAYMENT_TYPE varchar2(0),
	ORDER_UPDATED_DATE date DEFAULT SYSDATE,
	RECEIVE_DATE date,
	USER_NO number(4,0) NOT NULL,
	ADDRESS_NO number(4,0) NOT NULL,
	PRIMARY KEY (ORDER_NO)
);


CREATE TABLE SEMI_PRODUCTS
(
	PRODUCT_NO number(4) NOT NULL,
	PRODUCT_NAME varchar2(255) NOT NULL,
	PRODUCT_IMAGE_NAME varchar2(255) NOT NULL,
	PRODUCT_DESCRIPTION long,
	PRODUCT_CUSTOMER_PRICE number(8),
	PRODUCT_SELL_PRICE number(8) NOT NULL,
	PRODUCT_DEPOSIT_POINT number(8) NOT NULL,
	PRODUCT_DELIVERY_FEE number(8) NOT NULL,
	PRODUCT_STOCK number(8) NOT NULL,
	PRODUCT_ON_SELL char(1),
	PRODUCT_CREATED_DATE date DEFAULT SYSDATE,
	PRODUCT_UPDATED_DATE date DEFAULT SYSDATE,
	CATEGORY_NO number(4,0) NOT NULL,
	PRIMARY KEY (PRODUCT_NO)
);


CREATE TABLE SEMI_PRODUCT_CATEGORY
(
	CATEGORY_NO number(4,0) NOT NULL,
	CATEGORY_NAME varchar2(255) NOT NULL,
	PRIMARY KEY (CATEGORY_NO)
);


CREATE TABLE SEMI_REVIEWS
(
	REVIEW_NO number(4,0) NOT NULL,
	USER_NO number(4,0) NOT NULL,
	PRODUCT_NO number(4) NOT NULL,
	REVIEW_TITLE varchar2(255),
	REVIEW_CONTENT long,
	REVIEW_CREATED_DATE date,
	PRIMARY KEY (REVIEW_NO)
);


CREATE TABLE SEMI_USERS
(
	USER_NO number(4,0) NOT NULL,
	USER_ID varchar2(20) NOT NULL UNIQUE,
	USER_PASSWORD char(64) NOT NULL,
	USER_EMAIL varchar2(255) NOT NULL,
	USER_NAME varchar2(100) NOT NULL,
	USER_PHONE varchar2(20) NOT NULL,
	-- 남성  MALE     = 'M'
	-- 여성  FEMALE  =  'F'
	-- 기타  OTHER   =  'O'
	USER_GENDER char(1),
	USER_BIRTHDAY date,
	USER_ADMIN char(1),
	USER_ADDRESS varchar2(255),
	USER_DELETED char(1) DEFAULT 'N',
	USER_CREATED_DATE date DEFAULT SYSDATE,
	USER_UPDATED_DATE date DEFAULT SYSDATE,
	USER_GRADE varchar2(20) NOT NULL,
	PRIMARY KEY (USER_NO)
);


CREATE TABLE SEMI_USER_ADDRESS
(
	ADDRESS_NO number(4,0) NOT NULL,
	ADDRESS_NAME varchar2(255) NOT NULL,
	POSTAL_CODE char(5) NOT NULL,
	ADDRESS varchar2(255) NOT NULL,
	ADDRESS_DETAIL varchar2(255) NOT NULL,
	TEL varchar2(20) NOT NULL,
	ADDRESS_CREATED_DATE date DEFAULT SYSDATE,
	USER_NO number(4,0) NOT NULL,
	PRIMARY KEY (ADDRESS_NO)
);


CREATE TABLE SEMI_USER_POINTS
(
	USER_NO number(4,0) NOT NULL,
	USER_TOTAL_POINT number(8),
	USER_USED_POINT number(8),
	USER_AVAILABLE_POINT number(8),
	USER_UNUSED_POINT number(8)
);


CREATE TABLE SEMI_USER_POINT_HISTORIES
(
	HISTORY_NO number(4,0) NOT NULL,
	HISTORY_TITLE varchar2(255),
	POINT_AMOUNT number(8),
	HISTORY_CREATED_DATE date DEFAULT SYSDATE,
	USER_NO number(4,0) NOT NULL,
	PRIMARY KEY (HISTORY_NO)
);


CREATE TABLE SEMI_WISH_PRODUCTS
(
	WISH_ITEM_NO number(4,0) NOT NULL,
	USER_NO number(4,0) NOT NULL,
	PRODUCT_NO number(4) NOT NULL,
	WISH_ITEM_CREATED_DATE date DEFAULT SYSDATE,
	PRIMARY KEY (WISH_ITEM_NO)
);



/* Create Foreign Keys */

ALTER TABLE ORDER_ITEM
	ADD FOREIGN KEY (ORDER_NO)
	REFERENCES SEMI_ORDERS (ORDER_NO)
;


ALTER TABLE ORDER_ITEM
	ADD FOREIGN KEY (PRODUCT_NO)
	REFERENCES SEMI_PRODUCTS (PRODUCT_NO)
;


ALTER TABLE SEMI_CART_ITEMS
	ADD FOREIGN KEY (PRODUCT_NO)
	REFERENCES SEMI_PRODUCTS (PRODUCT_NO)
;


ALTER TABLE SEMI_REVIEWS
	ADD FOREIGN KEY (PRODUCT_NO)
	REFERENCES SEMI_PRODUCTS (PRODUCT_NO)
;


ALTER TABLE SEMI_WISH_PRODUCTS
	ADD FOREIGN KEY (PRODUCT_NO)
	REFERENCES SEMI_PRODUCTS (PRODUCT_NO)
;


ALTER TABLE SEMI_PRODUCTS
	ADD FOREIGN KEY (CATEGORY_NO)
	REFERENCES SEMI_PRODUCT_CATEGORY (CATEGORY_NO)
;


ALTER TABLE SEMI_CART_ITEMS
	ADD FOREIGN KEY (USER_NO)
	REFERENCES SEMI_USERS (USER_NO)
;


ALTER TABLE SEMI_ORDERS
	ADD FOREIGN KEY (USER_NO)
	REFERENCES SEMI_USERS (USER_NO)
;


ALTER TABLE SEMI_REVIEWS
	ADD FOREIGN KEY (USER_NO)
	REFERENCES SEMI_USERS (USER_NO)
;


ALTER TABLE SEMI_USER_ADDRESS
	ADD FOREIGN KEY (USER_NO)
	REFERENCES SEMI_USERS (USER_NO)
;


ALTER TABLE SEMI_USER_POINTS
	ADD FOREIGN KEY (USER_NO)
	REFERENCES SEMI_USERS (USER_NO)
;


ALTER TABLE SEMI_USER_POINT_HISTORIES
	ADD FOREIGN KEY (USER_NO)
	REFERENCES SEMI_USERS (USER_NO)
;


ALTER TABLE SEMI_WISH_PRODUCTS
	ADD FOREIGN KEY (USER_NO)
	REFERENCES SEMI_USERS (USER_NO)
;


ALTER TABLE SEMI_ORDERS
	ADD FOREIGN KEY (ADDRESS_NO)
	REFERENCES SEMI_USER_ADDRESS (ADDRESS_NO)
;



